### ISSUE TITLE
why do not use in safari 14   

### ISSUE THREAD

**Issue by anthonyyuan** [alemart/speedy-vision-js#10]
hi:
   I find my safari 14  may use webgl2.0 ,Iwhen I  use image to test it ,it work well ,but when I use camera, I get one picture ,and do not continiu to work, I use iphone12,can u give me some ad?

**Comment by alemart** [comment]
I don't know. I don't have access to Safari 14 at the moment. Safari is not supported for now.

As linked in #9 , [caniuse](https://caniuse.com/?search=webgl2) states that WebGL2 is available under an experimental flag in Safari 14. This suggests support might be partial.

If you find that other video-based demos do work, then you may draw your camera frames to a canvas in order to experiment with it. Let me know if you succeed.

**Comment by alemart** [comment]
Closed due to inactivity.
