### ISSUE TITLE
mask construction

### ISSUE THREAD

**Issue by under-score** [alemart/speedy-vision-js#23]
How can I mask pure black & white pixel from being included in feature tracking?

**Comment by under-score** [comment]
Thank you - just updated to the new pipeline. 

Unfortunately ORB keypoint detection is no more working now as
`const detector = Speedy.Keypoint.Detector.ORB();`
produces a
`uncaught (in promise) TypeError: Speedy.Keypoint.Detector.ORB is not a function at window.onload`

Anyway -- I always start with multi image panels (whole page screenshots see the link above) -- no need for any impainting -- only quick keypoint detection...

As suggested, I tried now the FAST detector after the median filter but could also not mask/exclude black and and white pixel positions. So what about the idea of looking up lets say the 5x5 kernel of each keypoint if it includes several black and white pixel?

**Comment by alemart** [comment]
Hi. Thank you for your reply.

Please use `Speedy.Keypoint.Descriptor.ORB()` instead. My [ORB demo](https://alemart.github.io/speedy-vision-js/demos/orb-features.html) has a fully working pipeline that may be of help. There was a error in my README, where it said detector instead of descriptor. I have just fixed it.

> Anyway -- I always start with multi image panels (whole page screenshots see the link above) -- no need for any impainting -- only quick keypoint detection...

If you use an image like the one below, you'll be getting corners at 7,8,16,18... due to the very nature of the corner detector. It's designed to catch that sort of thing. My suggestion is that you crop your image and apply the keypoint detector only in the relevant parts of it. Instead of working with whole page screenshots, work with the individual images of the cells separately.

![139379541-89ea9ec0-5575-4f7b-b188-dad8dc12ec2b](https://user-images.githubusercontent.com/221477/139752167-8baef049-4e67-41e9-ba0c-bc89f1b54193.jpg)

**Comment by under-score** [comment]
Sure, there is nothing bad with detecting corners ;-)
IMHO cropping/segmentation by a realtime JS pipeline does not work out of the box as with C++ or Python. 
Thank you again for your thoughts.
